---
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: configure MySQL listener on all IPs
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address= {{ ansible_eth0.ipv4 }}"
  notify: restart mysql

- name: ensure mysql-server started
  service: name=mysql state=started enabled=yes

- name: create demo database
  mysql_db: name=demo state=present

- name: create demo db user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present