---
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes

- name: configure MySQL listener on all IPs
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address= {{ansible_eth1.ipv4.address}}"
  notify: restart mysql

- name: ensure mysql-server started
  service: name=mysql state=started enabled=yes

- name: create database
  mysql_db: name={{ db_name }} state=present

- name: create demo db user
  mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_user_name }}.*:ALL 
              host='{{ db_user_host }}' state=present